config/routes.rb
Exam::Application.routes.draw do
  get "game/index"
  post "game/play"
  post "game/cancelar"

  root :to => 'game#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :session_id, :table
  serialize :table, Array
  attr_accessor :winner

  USER_SYMBOL = 'X'
  SERVER_SYMBOL = 'O'

  #returns game status
  def status
    {
      winner: @winner,
      table: self.table
    }
  end

  def init_table
    self.table = []
    self.table << [nil,nil,nil]
    self.table << [nil,nil,nil]
    self.table << [nil,nil,nil]
    self.save!
  end

  # plays the symbol and positions Ejem. X: [0,1]
  def play(new_mark)
    init_table if self.table.empty?

    indices = new_mark.split(',').map{|i| i.to_i}

    self.table[indices.first][indices.last] = 'X'

    if user_won?
      @winner = "Usuario gano"
    else
      #let server play
      server_play
      @winner = "Server gano" if server_won?
    end
    self.save!
  end

  def server_play
    indices = choose_cell
    self.table[indices.first][indices.last] if indices

  end

  def choose_cell
    0.upto(2) do |vertical_i|
      0.upto(2) do |horizontal_i|
        indices = [vertical_i, horizontal_i] 
        cell_value = self.table[indices.first][indices.last]
        if cell_value.nil?
          self.table[indices.first][indices.last] = 'O'
          return indices 
        end
      end
    end
    false
  end

  def cancel
    init_table
  end

  def server_won?
    check_diagonal_win(SERVER_SYMBOL) || check_vertical_win(SERVER_SYMBOL) || check_horizontal_win(SERVER_SYMBOL)
  end

  def user_won?
    check_diagonal_win(USER_SYMBOL) || check_vertical_win(USER_SYMBOL) || check_horizontal_win(USER_SYMBOL)
  end

  #check for diagonal wins
  def check_diagonal_win(symbol)
    return true if self.table[0][0] == symbol && self.table[1][1] == symbol && self.table[2][2] == symbol
    return true if self.table[0][2] == symbol && self.table[1][1] == symbol && self.table[2][0] == symbol
    false
  end

  #check for vertical wins
  def check_vertical_win(symbol)
    0.upto(2).each do |column|
      return true if self.table[0][column] == symbol && self.table[1][column] == symbol && self.table[2][column] == symbol
    end
    false
  end

  #check for horizontal wins
  def check_horizontal_win(symbol)
    self.table.each do |row|
      return true if row[0] == symbol && row[1] == symbol && row[2] == symbol
    end
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    @game = Game.find_or_create_by_session_id(request.session_options[:id])
  end

  def play
    @game = Game.find_by_session_id(request.session_options[:id])
    @game.play(params[:new_mark])
    render json: @game.status
  end

  def cancelar
    @game = Game.find_by_session_id(request.session_options[:id])
    @game.cancel
    render json: @game.status
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game/index.html.erb
<h1>TicTacToc</h1>
<table id="tictac" data-playurl="<%= game_play_path %>">
  <tr>
    <td id="cell00" data-cell='0,0'>?</td>
    <td id="cell01" data-cell='0,1'>?</td>
    <td id="cell02" data-cell='0,2'>?</td>
  </tr>
  <tr>
    <td id="cell10" data-cell='1,0'>?</td>
    <td id="cell11" data-cell='1,1'>?</td>
    <td id="cell12" data-cell='1,2'>?</td>
  </tr>
  <tr>
    <td id="cell20" data-cell='2,0'>?</td>
    <td id="cell21" data-cell='2,1'>?</td>
    <td id="cell22" data-cell='2,2'>?</td>
  </tr>
</table>

<h2 id="game_status">
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Exam" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">TicTacToc</a>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Nuevo Juego", game_cancelar_path, id: "cancelar"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>